### ISSUE TITLE
Request for translation on filipino

### ISSUE THREAD

**Issue by agentzero1** [Microsoft/Localization#10]
I want to contribute in translation

**Comment by danyeh** [comment]
@agentzero1, Thank you for showing interest for contributing!
One opportunity is vscode UI localization. See here for procedure to request new language in Transifex where host the translation projects. https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by danyeh** [comment]
Thank you for creating the request (issue). https://github.com/Microsoft/vscode/issues/43218
