### ISSUE TITLE
1.43.8版本 安装后无法设置成中文

### ISSUE THREAD

**Issue by AcidShen** [microsoft/Localization#100]
更新了语言包后发现界面语言退回了默认的英文，切换回1.43.7版本后问题就消失了

**Comment by zzh-blog** [comment]
是的，我在刚刚升级插件时也遇到了这样问题，1.43.8版本的翻译包似乎存在一些细微的错误，导致无法替换原生的英文界面

**Comment by hecoco** [comment]
设置历史版本就可以了

**Comment by janbaltus** [comment]
Please update to 1.43.9. There was incorrect BOM for one file causing crash

**Comment by lsbbd** [comment]
@janbaltus 1.43.9 fixed，thank you

**Comment by CallMeR** [comment]
version 1.43.1 也有中文设置失败问题啊！

**Comment by janbaltus** [comment]
please use 1.43.9

**Comment by AcidShen** [comment]
> Please update to 1.43.9. There was incorrect BOM for one file causing crash

更新1.43.9版本后问题解决了，十分感谢
