### ISSUE TITLE
Inconsistent German translations in VS Code's Git panel

### ISSUE THREAD

**Issue by FloEdelmann** [microsoft/Localization#101]
found here:  
![Screenshot_2020-03-20_18-32-13](https://user-images.githubusercontent.com/202916/77190367-68fbc780-6ad9-11ea-8bb0-6132dd2ff0d5.png)

"Commit *Staged* (Signed Off)" is (correctly) translated with "*Bereitgestelltes* committen (unterzeichnet)". "Staged changes" is also correctly translated with "Bereitgestellte Änderungen".

The other two ("Commit Staged" and "Commit Staged (Amend)") should also use the word "Bereitgestelltes" instead of "Gestaffelt", which has a different meaning (rather like *staggered*).

| Source | Current translation | Suggested translation |
| ------ | ------------------- | --------------------- |
| Commit Staged | ~Gestaffelt committen~ | Bereitgestelltes committen |
| Commit Staged (Amend) | ~Gestaffelt committen (Ändern)~ | Bereitgestelltes committen (Ändern) |

![Screenshot_2020-03-20_18-26-24](https://user-images.githubusercontent.com/202916/77189739-5634c300-6ad8-11ea-9b81-abd540f18a26.png)

Unfortunately, I can't suggest changes to existing translations on MLCP, so I searched what to do instead. It took me quite some time to find the [instructions](https://github.com/Microsoft/Localization/wiki/Need-help-or-report-an-issue#reporting-an-incorrect-translation), maybe you can make them more obvious somewhere else in VS Code's repo wiki.

**Comment by lukaschal** [comment]
On review.

SRC: Commit Staged (Signed Off)
TGT: Bereitgestelltes committen (unterzeichnet)

SRC: Commit Staged (Amend)
TGT: Gestaffelt committen (Ändern)

SRC: Commit Staged
TGT: Gestaffelt committen

**Comment by lukaschal** [comment]
Fixed.

SRC: Commit Staged (Signed Off)
TGT: Gestagetes committen (abgezeichnet)

SRC: Commit Staged (Amend)
TGT: Gestagetes committen (Ändern)

SRC: Commit Staged
TGT: Gestagetes committen

**Comment by FloEdelmann** [comment]
Thanks, the changes have landed in the stable version.

However, there are now other inconsistencies:

* "Staged changes" = "*Bereitgestellte* Änderungen" vs. "Commit staged" = "*Gestagetes* committen"
* "Commit all (signed)" = "Alle committen (*unterzeichnet*)" vs. "Commit staged (signed)" = "Gestagetes committen (*abgezeichnet*)"

I think those are not as important as the original issue, but still worth noting.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.


Source Term
--
There are no staged changes to   commit.\n\nWould you like to automatically stage all your changes and commit   them directly?
STAGED CHANGES
Staged Changes
Commit Staged (Signed Off)
Always show the Staged Changes resource   group.
Commit all changes when there are no   staged changes.


Translation
--
Es sind keine gestageten Änderungen zum   Committen vorhanden.\r\n\r\nMöchten Sie alle Ihre Änderungen automatisch   stagen und direkt committen?
GESTAGETE ÄNDERUNGEN
Gestagete Änderungen
Gestagetes committen (signiert)
Ressourcengruppe für gestagete Änderungen   immer anzeigen.
Alle Änderungen committen, wenn keine   gestageten Änderungen vorhanden sind.

**Comment by FloEdelmann** [comment]
In the April Update (v1.45.0), all the translations have been fixed. Thank you!
