### ISSUE TITLE
Arabic Localization

### ISSUE THREAD

**Issue by MNAJIM75** [microsoft/Localization#102]
**_Hello Microsoft._**
Could you please add Arabic to the Localization list?
I signed up to the localization website, and chooses the Arabic as a translating language, but there were nothing to translate.

# So Please add the Arabic Language!

**Comment by janbaltus** [comment]
@weeteckt

**Comment by shrijap** [comment]
Hi @MNAJIM75 
Thank you for reaching out to us, and apologies for the delayed response! We are currently working on bringing you a new, more robust, localization platform and have decommissioned MLCP. As per this, we are placing new language requests on hold for the time being. Please keep an eye out on the Wiki for more updates on this. 
Best, 
Shrija
