### ISSUE TITLE
Explorer dont show the buttons with spanish language

### ISSUE THREAD

**Issue by MartinJesus23** [microsoft/Localization#103]
### Some images
![VScode bug](https://user-images.githubusercontent.com/26811053/77476521-0711c980-6e1b-11ea-9cfe-3261f24bdbf7.png)
![VSCode Bug Inspector](https://user-images.githubusercontent.com/26811053/77476623-2f99c380-6e1b-11ea-8eb2-8f0a254447d5.png)
**Setting language in English**
![Image](https://user-images.githubusercontent.com/26811053/77476845-a8008480-6e1b-11ea-963f-d808d63b5e1b.png)
![imagen](https://user-images.githubusercontent.com/26811053/77477010-fca3ff80-6e1b-11ea-8985-90c612f4072f.png)

**Comment by lukaschal** [comment]
SRC: You have not yet opened a folder. [Open Folder](command:{0})
TGT: Todavía no ha abierto una carpeta. [Abrir carpeta] (command:{0})

SRC: You can also clone a repository from a URL. To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm). [Clone Repository](command:git.clone)
TGT: También puede clonar un repositorio desde una dirección URL. Para obtener más información sobre cómo usar Git y el control de código fuente en VS Code [lea nuestros documentos](https://aka.ms/vscode-scm). [Clonar repositorio] (command:git.clone)

**Comment by lukaschal** [comment]
Fixed.

**Comment by janbaltus** [comment]
Fix will be present starting LP 1.44.1

**Comment by MartinJesus23** [comment]
Thanks!
