### ISSUE TITLE
VSCode Chinese (Simplified) non-standard marks

### ISSUE THREAD

**Issue by OkazakiNagisa** [microsoft/Localization#104]
exists both full-width and half-width brackets, colons, etc

![图片](https://user-images.githubusercontent.com/7100178/82664669-c7bdf880-9c64-11ea-8475-9fee541585a0.png)
![图片](https://user-images.githubusercontent.com/7100178/82664695-d4425100-9c64-11ea-83d5-452867f3242d.png)

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed. Single-Byte characters used consistently now.

**Comment by OkazakiNagisa** [comment]
Thanks
