### ISSUE TITLE
questions: machine translation

### ISSUE THREAD

**Issue by liuxilu** [microsoft/Localization#105]
The wiki says
> you will no longer be able to Edit and modify MT content via Pull Request.

- What MT engine do you use, not just connecting to Bing translate, but have one just for doc translation, right?
- How long is long, forever or for some time?
  - I have heard neural engine can either machine learing or manually input, is it?
  - If so, how do I do?
- Unable via PR, then any other way?
- Can't edit MT, then is it possible to change MT docs to HT?
  - Obviously, more (qualified) HT, more MT quality.
  - If not, for example .Net docs 11248/14172 MT, god bless you, my poor doc.
  - If not, thus MT quality impoved, but whole quality and its superior limit largely dropped.
  - If not, It seems there is MT's playground, not docs for human reading.
  - If not, please consider enable it, no technical problems for sure.

**Comment by janbaltus** [comment]
@liuxilu  please clarify which project do you mean?
Please shere link to Wiki page

**Comment by liuxilu** [comment]
For my case, it's [dotnet/docs.zh-cn](https://github.com/dotnet/docs.zh-cn), and the [wiki page](https://github.com/microsoft/Localization/wiki/MTEngineUpdate) applies for all localization projects, I think.

**Comment by janbaltus** [comment]
@dbaeumer and @weeteckt can you please answer this general question?

**Comment by shrijap** [comment]
Hi @liuxilu 

Thank you for reaching out to us with these questions. Please find answers to your questions below: 

• What MT engine do you use, not just connecting to Bing translate, but have one just for doc translation, right?
**We have an instance of the MSR translation engine trained specifically with human translated content for our products, to ensure best possible machine translation quality possible for our content type.**
• How long is long, forever or for some time?
**Unfortunately, we will not be re-enabling MT community contribution in the near future but we hope to resume at some time down the line. **
• I have heard neural engine can either machine learing or manually input, is it?
If so, how do I do?
**We retrain our translation engine periodically with freshest human translated content. Customers cannot update the machine translation engine directly.**
• Unable via PR, then any other way?
**No, we currently cannot support feedback on machine translated content. If you found a generic issue that applies to many topics, you can open a feedback (GitHub issue) or Site Feedback. **
• Can't edit MT, then is it possible to change MT docs to HT?
**Human translation is very costly; with the scope of our documentation we cannot support translating all content with human quality. **
• Obviously, more (qualified) HT, more MT quality.
If not, for example .Net docs 11248/14172 MT, god bless you, my poor doc.
If not, thus MT quality impoved, but whole quality and its superior limit largely dropped.
If not, It seems there is MT's playground, not docs for human reading.
If not, please consider enable it, no technical problems for sure.
**Please be assured that we are constantly trying to improve the machine translation quality, and will apply new technologies as they become available, and after we have tested them.**

**Comment by shrijap** [comment]
Hi @liuxilu 

Thank you for reaching out to us with these questions. Please find answers to your questions below: 

• What MT engine do you use, not just connecting to Bing translate, but have one just for doc translation, right?
**We have an instance of the MSR translation engine trained specifically with human translated content for our products, to ensure best possible machine translation quality possible for our content type.**
• How long is long, forever or for some time?
**Unfortunately, we will not be re-enabling MT community contribution in the near future. But please do let us know if there are topics that you think can benefit from HT and we can take that under review. **
• I have heard neural engine can either machine learing or manually input, is it?
If so, how do I do?
**We retrain our translation engine periodically with freshest human translated content. Customers cannot update the machine translation engine directly.**
• Unable via PR, then any other way?
**No, we currently cannot support feedback on machine translated content. If you found a generic issue that applies to many topics, you can open a feedback (GitHub issue) or Site Feedback. **
• Can't edit MT, then is it possible to change MT docs to HT?
**Human translation is very costly; with the scope of our documentation we cannot support translating all content with human quality. **
• Obviously, more (qualified) HT, more MT quality.
If not, for example .Net docs 11248/14172 MT, god bless you, my poor doc.
If not, thus MT quality impoved, but whole quality and its superior limit largely dropped.
If not, It seems there is MT's playground, not docs for human reading.
If not, please consider enable it, no technical problems for sure.
**Please be assured that we are constantly trying to improve the machine translation quality, and will apply new technologies as they become available, and after we have tested them.**

**Comment by liuxilu** [comment]
Sorry for my late response.
>trained specifically with human translated content for our products

"our products", does it mean All microsoft products?
> **Human translation is very costly; with the scope of our documentation we cannot support translating all content with human quality. **

I know. I'm not thinking of cancel all MT but a certain page someone like me would like to translate and improve. For example if I see a MT page is not such perfect, then I request a MT to HT and you do that or there's a switch, then I can and will do improve the translation, just cost me. And this can improve MT as well.

@shrijap

**Comment by liuxilu** [comment]
@dbaeumer @weeteckt

**Comment by dbaeumer** [comment]
May be @danyeh can help. I have no idea how the translation process works. I only know how VS Code consumes the translations.
