### ISSUE TITLE
Localization/Translation into Filipino

### ISSUE THREAD

**Issue by Cyyy1998** [Microsoft/Localization#11]
Good day

Can I translate this project into my native language which is Filipino

**Comment by aldonetti** [comment]
hello @Cyyy1998 , which project are you interested in? VSCode I assume? If so, could you please go to this page https://www.transifex.com/microsoft-oss/vscode-editor/languages/ , click on the "requested languages" link and add it to the list? 
thanks for your interest and please do let me know if you have questions
![image](https://user-images.githubusercontent.com/2181885/36153309-227b801e-10ce-11e8-951e-fdfc4bd8c356.png)
 or issues

**Comment by aldonetti** [comment]
closing for now, unless there are further questions/issues

**Comment by danyeh** [comment]
@Cyyy1998 , please vote by putting your Transifex account info in issue comment. 
https://github.com/Microsoft/vscode/issues/43218

**Comment by aldonetti** [comment]
thank you @danyeh for the correction. sorry for the wrong info @Cyyy1998
