### ISSUE TITLE
right arrow key automatically submits new translation

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#16]
On https://envelope-community.azurewebsites.net, my new translation suggestion was submitted prematurely when I hit the right arrow key. I was trying to select a word (shift+ right arrow key) to cut/paste later to reorder some content. Selecting with mouse is cumbersome.

**Comment by danyeh** [comment]
Adding @khoiph1 to double check.

**Comment by khoiph1** [comment]
@jiangsheng Thank you for reporting the issue. We are looking into this.

**Comment by khoiph1** [comment]
@jiangsheng We have fixed the issue. Shift + Right Arrow key will not submit a suggestion. A shortcut key for submitting a translation is Ctrl + Right Arrow key. Thank you for report the issue to us.

**Comment by jiangsheng** [comment]
can you skip control +shift arrow key?
