### ISSUE TITLE
duplicate entries in word list

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#17]
![20180502190313](https://user-images.githubusercontent.com/1025946/39554992-8d6c3594-4e3b-11e8-8f99-2dc5832aa5c8.png)

OK and No appear twice in the pending words list.

**Comment by aldonetti** [comment]
thank you for the feedback @jiangsheng - these are popular strings that appear multiple times in the software and are not de-duplicated. @khoiph1 anything we can do about it?

**Comment by benedetti** [comment]
comment allez vous

**Comment by microsoftl10n** [comment]
Those strings come from multiple source files. Thus, we cannot remove them.

**Comment by khoiph1** [comment]
Those strings come from multiple source files. We need them there.
