### ISSUE TITLE
HTML code in source string

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#18]
![20180508152426](https://user-images.githubusercontent.com/1025946/39781277-57450c3c-52d4-11e8-85ec-99b56bee384a.png)

the extractor should be able to separate HTML code and localizable string.

**Comment by khoiph1** [comment]
@Monasr please follow up with Karl to remove the non-breaking space if we don't need it in this string.

**Comment by khoiph1** [comment]
This non-breaking space is part of the source string. Please include it in the translation.
