### ISSUE TITLE
punctuation as source string

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#19]
just found "!" (U+0021) in the list of source string for Team Explorer Everywhere. It is another case that I think should have an option to vote the source string out as there is no universal translation. Normally the exclamation mark could be translated as “！” (U+FF01) in Chinese, however if it is part of code (e.g. if a != b) then the exclamation mark should not be translated.

**Comment by praveeg** [comment]
@jiangsheng - I confirmed that these exclamation marks are just single exclamations used for a sentence and not used as a!=b. Hope this answers your questions.

**Comment by jiangsheng** [comment]
The question is a punctuation like this should not be a source string by itself.

**Comment by praveeg** [comment]
Agreed that the punctuation should be a source string by itself. I created a bug for the product team to remove this string and concatenate '!' with strings where it is being used.

**Comment by aldonetti** [comment]
hi @praveeg , just checking -  is this done? thanks!

**Comment by praveeg** [comment]
@aldonetti - the question is answered but this is pending bug fix from core team. we can resolve this ticket here and I can come back to update once the bug is fixed.
