### ISSUE TITLE
Please add vscode-ja comunnity info to wiki

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/Localization#2]
We made a slack Japanese team for VSCode translation. Will you put this information on the wiki?
url: https://vscode-ja.slack.com/shared_invite/MTczMzQzODQ1NzkyLTE0OTMxMDY0OTUtZmYzMDU4MDQ1MA

**Comment by danyeh** [comment]
Thank you @YuichiNukiyama san for the initiative! I added to contributor page. Please review here.
https://github.com/Microsoft/Localization/wiki/VS-Code-Community-Localization-Contributors

**Comment by YuichiNukiyama** [comment]
Thanks @danyeh san :smile:
