### ISSUE TITLE
vs code 1.24  not supporting Chinese (Simplified) Language Pack for Visual Studio Code

### ISSUE THREAD

**Issue by jojoku** [Microsoft/Localization#24]
vs code 1.24  not supporting Chinese (Simplified) Language Pack for Visual Studio Code

**Comment by danyeh** [comment]
@jojoku , thank you for reporting this issue! This issue was fixed with Chinese language pack 1.24.1. Please update to this new version within VS Code or install from https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans.
