### ISSUE TITLE
The final punctuation mark ' in your translation does not match the source.

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/Localization#25]
source string is 
Disabling Alert '{0}'
from SQL Tools for Linux.

aren't we supposed to translate punctuations as well (#19)? E.g. apostrophe (U+0027)->full width apostrophe (U+ff07)

**Comment by aldonetti** [comment]
Hello @jiangsheng  thank you for your request and sorry for the belated reply.
You could do that if you wanted to
