### ISSUE TITLE
issue in the french plugin

### ISSUE THREAD

**Issue by Navis-Raven** [Microsoft/Localization#28]
In the file menu there is an issue for the french plugin, the Ctrl shortcuts commands are at the wrong place. 

![image](https://user-images.githubusercontent.com/15887222/44535377-235afb00-a6fa-11e8-8221-8adf57267a29.png)

I've tested two of them and they are wrong and not valid (Ctrl + K Ctrl + O ; and Ctrl + K S)

I don't know if there is this issue in other menues

**Comment by danyeh** [comment]
@Navis-Raven , thank for your feedback! Could you please open the issue in vscode repo instead?
It doesn't look like translation issue. Our translation is hosted in Transifex, I could not find these Ctrl shortcut. Some info of localization: https://aka.ms/vscodeloc.

**Comment by Navis-Raven** [comment]
opened here https://github.com/Microsoft/vscode/issues/60391
