### ISSUE TITLE
The leaderboard does not have my account.

### ISSUE THREAD

**Issue by stulzq** [Microsoft/Localization#30]
My points has exceeded 100, but the leaderboard has not had my name. I have been observing for a few days.I sent an email to mscommunityprogram@microsoft.com on October 22 to explain the problem, but did not receive a response.
My account information：
````
Username: Zhiqiang Li
Org: Microsoft MVP
Email: xchenmaster@hotmail.com
````
Thanks.

**Comment by khoiph1** [comment]
Closing this issue as I followed up with Zhiqiang on email.
