### ISSUE TITLE
My account appears on the wrong leaderboard

### ISSUE THREAD

**Issue by chenjd** [Microsoft/Localization#31]
My account information:

Username: jiadong chen
Org: Microsoft MVP
Email: shaun.chan@hotmail.com

but my account appears on contributor instead of mvp contributor.

**Comment by aldonetti** [comment]
thank you @chenjd for letting us know - we are fixing it.

**Comment by shrijap** [comment]
Hi, 

Apologies for the delayed response! You should be able to see your name on the MVP side of the leaderboard now. Thank you for contributing to Microsoft!
