### ISSUE TITLE
My account appears on the wrong leaderboard

### ISSUE THREAD

**Issue by Fujiwo** [Microsoft/Localization#34]
My account appears on the wrong leaderboard.

My account information:

Username: Fujio Kojima
Org: Microsoft MVP
Email: fujiwo@hotmail.co.jp

My account appears on contributor instead of mvp contributor.

**Comment by terrysheng** [comment]
@Fujiwo Thank you so much for your update, we are fixing it soon :)

**Comment by shrijap** [comment]
Hi, 

Apologies for the delayed response! You should be able to see your name on the MVP side of the leaderboard now. Thank you for contributing to Microsoft!
