### ISSUE TITLE
Revise registration form - No, I do NOT want to receive newsletters

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/Localization#36]
Please revise the text of the last checkbox in the registration form:

![mlcp](https://user-images.githubusercontent.com/9283914/49975059-5a207f80-ff3c-11e8-8511-5be4d681d3fe.png)
<br/>

### NO, I DO *NOT* WANT TO RECEIVE E-MAILS OR NEWSLETTERS!
<br/>

**Comment by aldonetti** [comment]
thank you for your suggestion @SetTrend - we are looking into it

**Comment by aldonetti** [comment]
@SetTrend - hello again Axel. I have checked and, as strange as it may seem, you are not going to be enrolled into any newsletter. It's "standard" legal text we have used, to ensure we can reach out to you with communications which are related to the activity itself - you are not going to receive any marketing/sales email or newsletter by checking that flag.
In general, with any Microsoft Account, you can always decide which newsletters/mailing lists you receive info from, by visiting the "Manage Communications Permissions" from your Microsoft Account information page
![Manage Communications Permissions](https://user-images.githubusercontent.com/2181885/50040131-eb2b4f80-003d-11e9-8231-40cb54384add.png)
And specifically for the MLCP platform, once you are registered into the portal, you can go back and select the option to not receive any email - see below,
![MLCP Account Settings](https://user-images.githubusercontent.com/2181885/50040170-b8358b80-003e-11e9-8698-681d846f5376.png)

Do you think that is sufficient? We want to make sure that community members are clear that we are not trying to market/sell anything here 😊

Feedback is always welcome - thank you!

Aldo

**Comment by SetTrend** [comment]
Thank you for enlightening me, Aldo.

What e-mails in particular would I unsubscribe from if I chose to "unsubscribe the emails from the Community"?

**Comment by aldonetti** [comment]
Sorry for the delay Axel - you would be unsubscribing from *all* emails.

**Comment by SetTrend** [comment]
@aldonetti : Would this option also include switching off notification e-mails regarding my particular translations? I would still want to receive notification e-mails concerning my particular translations.

**Comment by yannicka** [comment]
Even if we can unsubscribe from the newsletter after registration, this is not GDPR-friendly. That should be fixed.

**Comment by aldonetti** [comment]
sorry @SetTrend I had not seen your last question at the time - there usually isn't any communication about your translations, so no worries there. In any case there are new features upcoming in MLCp that will allow commenting of translations in the tool.

Thanks @yannica - I understand and I will open a request to review it (at least). I am sure it was reviewed by our legal department before being implemented, but an extra review does not hurt. I'll let you know how that goes. Thanks again for your input
