### ISSUE TITLE
Hungarian translation of VS Code in MLCP

### ISSUE THREAD

**Issue by qcz** [Microsoft/Localization#38]
As suggested in the latest announcement, I've signed up to the Microsoft Localization Community Platform to continue the localization of VS Code to Hungarian. However, the only project I see there is the "Azure - BatchExporter":
![firefox_2018-12-15_07-23-04](https://user-images.githubusercontent.com/304384/50039889-54a95f00-003a-11e9-976b-9f3f4cd0aa76.png)
There are no further instructions on [this page](https://github.com/Microsoft/Localization/wiki/How-to-contribute-to-Software#microsoft-localization-community-platform) on how to gain access to the VS Code project or who I have to contact to be able to see it.

**Comment by aldonetti** [comment]
@qcz - thank you Dániel !
the translation of VS Code will restart after the migration to the new platform
you can see the warning note in the [VSCode project page](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project)
![2018-12-15 08_35_33-visual studio code community localization project microsoft_localization wiki](https://user-images.githubusercontent.com/2181885/50040500-d8684900-0044-11e9-9bfc-1d3ef7d54b7f.png)
for now .. enjoy the Holidays! 😊
Thanks again for all you do!
Aldo
