### ISSUE TITLE
How to modify an accepted translation in MLCP?

### ISSUE THREAD

**Issue by Joelism** [Microsoft/Localization#39]
There're some mistranslations in VSCode zh-CN language pack, how can I submit an suggestion to correct it?

**Comment by aldonetti** [comment]
Hi @Joelism, you can open a GitHub Issue here (as you have done now) with the details of the existing translation and the proposed one. We will handle it. Thanks much for you help!

**Comment by Joelism** [comment]
Hi, after seeing https://github.com/Microsoft/vscode/issues/65534, I compared Chinese localization files before and after the platform transition, and noticed some of strings are changed inaccurately or for more inconsistencies. The number is pretty high actually, it may take a long time for me to report them all, I'll try my best.
Seriously, it's nice of you guys to review our translation, but did a bad job. Some of the changed strings seem to be machine-translated, some changes don't account for its context at all, and some don't make any sense.
