### ISSUE TITLE
MLCP: Cannot select another language

### ISSUE THREAD

**Issue by simonech** [Microsoft/Localization#40]
I just registered into the MLCP for the upcoming migration of VS Code from transifex.
This platform has so many less features, but the one I miss the most is the possibility to switch to another language. 
There 2 scenarios: 
 - I want to help in multiple languages (I'm Italian native speaker, but I also help with Latvian)
 - I want to be able to see how a source string has been translated to another language. English is a very simple language and same text can be translated in many different way. Seeing how other languages have "interpreted" the text makes it easier to translate.

**Comment by aldonetti** [comment]
Ciao @simonech - as yo uhave noticed, currently this is not possible. Let me ask if there's any available workaround. Please stay tuned and thanks!

**Comment by aldonetti** [comment]
Hi again, Simone - currently it is only possible by using two different accounts. I have logged a Feature request and I will let you know when it gets prioritised and out of the backlog. Thanks for your contributions!

**Comment by carstenhag** [comment]
Hey, is this still a thing? I know german, spanish and catalan, but now I am limited to german :/

**Comment by aldonetti** [comment]
thank you for your interest @carstenhag - it's great that you have such skills :) I would pick the one where I'm most fluent and go for that. Hopefully it's German, as the community seems to need a bigger hand there :) thanks!!

**Comment by IllusionMH** [comment]
Not sure why it is closed if still not implemented. And is there any progress in resolving this issue?

And I don't remember any warning about about inability to change language on registration page. Have I missed it?

This basically block user who would contribute to several languages and splits efforts by users who had to register other accounts for other languages.

Are there any technical limitations that prevent language switcher as one of dropdowns at the top of the page?

**Comment by carstenhag** [comment]
Probably closed because it gets tracked privately and the software is not open-source? Not sure.

When I registered 5 months ago there was no warning. That's why I was confused and commented here.

It's probably more difficult than adding a drop down :P.
