### ISSUE TITLE
Finnish language not having any data in MLCP, though it has been alive in Transifex for a year

### ISSUE THREAD

**Issue by SpecFI** [Microsoft/Localization#41]
VS Code - Finnish language is visible in MLCP, but it does not contain any data (no project nor strings).
It has been available for translations in Transifex side for some year by now.
Could someone get the Finnish running in MLCP side as well?
Thanks.

**Comment by aldonetti** [comment]
HI Petri, migration is in progress and will be done by end of December - you should find all strings available in January (in MLCP). Thanks!
