### ISSUE TITLE
Chinese (Traditional) Language Pack "大綱" Word Error

### ISSUE THREAD

**Issue by Korver2017** [Microsoft/Localization#42]
Chinese (Traditional) Language Pack for Visual Studio Code, It seems to have an error word which is in the description when the outline section is empty.

<img src="https://images2.imgbox.com/3b/23/OJuPDZ4X_o.png" alt="Word Error" title="One Word Error" width="70%" />

**Comment by lukaschal** [comment]
@Korver2017 Please, could you try verify this issue on latest CHT language pack and provide us ENU screenshot as well ?

**Comment by lukaschal** [comment]
Translated way mentioned below in a MLCP.

SRC: There are no editors open that can provide outline information.
TGT: 沒有開啟的編輯器可提供大網資訊。

**Comment by lukaschal** [comment]
Fixed.

New TGT: 沒有開啟的編輯器可提供大綱資訊。

**Comment by shawndon** [comment]
@Korver2017 Closing as fixed
