### ISSUE TITLE
Ukrainian language pack

### ISSUE THREAD

**Issue by romanfedyshyn** [Microsoft/Localization#44]
I want to take part in adding Ukrainian language support in vs code. What should I do for that?

**Comment by aldonetti** [comment]
Hi @romanfedyshyn - thank for your interest in supporting the Ukrainian-speaking developer community. Unfortunately we had enabled the Ukrainian language in VSCode but then after many months we noticed that there were too few contributors and the translation was never completed.
We could re-enable it again, but to be successful we should at least find a few more contributors, or else it's too big of a work for a single person ... Also, the first release is the bigger work, but VSCode is released every 3 weeks, so every month there are going to be new strings. It does require some persistence.
The more the better, of course, but I would say if you could find at least 3 volunteers, we would have higher chances of success. 
I'm closing this for now, but if you can find others that share your enthusiasm, please do let us know and we can work on it.
Thanks!

**Comment by borysl** [comment]
@romanfedyshyn @aldonetti @DmytroStepaniuk I once worked on the localization here https://github.com/microsoft/vscode-loc/tree/master/i18n/vscode-language-pack-uk

Do I have any option to compile it just for myself? I have kids that speak only Ukrainian, so I would like to do it myself
