### ISSUE TITLE
The name displayed on the right site does not correspond to the left account selected

### ISSUE THREAD

**Issue by t-deman** [Microsoft/Localization#45]
![image](https://user-images.githubusercontent.com/23658340/51910151-a6c9f800-23ce-11e9-8e8a-97972aadedc7.png)

It is always the same name staying on the right part. But the graphical pie is well updated.

**Comment by shrijap** [comment]
Hi Thierry, 
Thank you for reaching out to us! This issue is fixed now. We appreciate the feedback!
Shrija
