### ISSUE TITLE
Vscode contributors list contains vulgarisms

### ISSUE THREAD

**Issue by Venthe** [Microsoft/Localization#46]
In polish contributors you can see "chujcie toobchodzi" which roughly translates to "thefuc kyoucare". Please remove it

**Comment by Venthe** [comment]
![screenshot_20190207-041101](https://user-images.githubusercontent.com/1686874/52388462-c5935300-2a8e-11e9-89b4-a94e361e9447.png)

**Comment by aldonetti** [comment]
@Venthe thank you - we are removing it. we will be asking the user to fix his/her name. thanks again
