### ISSUE TITLE
Can't use different mail address from my Microsoft account

### ISSUE THREAD

**Issue by levrik** [Microsoft/Localization#48]
I don't want to show my mail address public. I have a different mail address for that.
I don't really want to create a separate Microsoft under a different mail address just for VS Code localization.

**Comment by aldonetti** [comment]
hi @levrik your email is not being showed publicly - where do you see that?
the user information that you see when you look at your profile in te MLCP tool (https://envelope-community.azurewebsites.net/auth/profile) it's only for you to see, it's not public.
thanks
