### ISSUE TITLE
中文版发行说明在哪？

### ISSUE THREAD

**Issue by tianxiemaochiyu** [Microsoft/Localization#5]
有没有中文版的发行说明，底部中文简体贡献者名单是什么意思

**Comment by danyeh** [comment]
Assume you mean VS Code release notes here. https://code.visualstudio.com/updates/v1_16#_thank-you. No, we don't have plan to localize release notes yet. I have sent the feedback to documentation owner. The localization contributors list who has contributed translation for this monthly release.
我想你指的是VS Code的发行说明。目前还没有本地化的计划。底部中文简体贡献者名单列出了所本月有提供了软件界面翻译的贡献者。
