### ISSUE TITLE
Corrections in Russian translation

### ISSUE THREAD

**Issue by mahovich** [Microsoft/Localization#50]
Since on https://envelope-community.azurewebsites.net/ cannot make changes to an existing translation, please correct the Russian translation:
"Разделить&" => "Разделить вверх"
"Отделить слева" => "Разделить слева"
"Отменить индексацию изменений" => "Отменить промежуточное изменение"
"Отменить индексацию всех изменений" => "Отменить все промежуточные изменения"
"Индексировать изменения" => "Применить промежуточное изменение"
"Хранить все промежуточные изменения" => "Применить все промежуточные изменения"

// it can not be translated, because In the translated technical literature, English terms are used.
"Фиксация" => "Commit"
"Отправить" => "Push"
"Отправить в:" => "Push to..."
"Получить" => "Pull"
"Получить из..." => "Pull from..."
"Получить (переместить изменения из одной ветви в другую)" => "Pull (Rebase)"

**Comment by aldonetti** [comment]
thank you for your suggestions @mahovich - we'll make changes on our end

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as per below.

SRC: Split Left
CORRECT: Разделить слева

SRC: Unstage Changes
CORRECT: Отменить промежуточное изменение

SRC: Unstage All Changes
TGT: Отменить индексацию всех изменений
CORRECT: Отменить все промежуточные изменения

SRC: Stage Changes
CORRECT: Индексировать изменения

SRC: Stage All Changes
CORRECT: Хранить все промежуточные изменения

**Comment by lukaschal** [comment]
The terms suggested to be left in English (like "commit", "push" and "pull") are actually localized in the general meaning on Git resources, including the Russian version of the book "ProGit". These translations are reflected in Term Studio and hence should remain as is.
