### ISSUE TITLE
zh-cn translation error

### ISSUE THREAD

**Issue by imba-tjd** [Microsoft/Localization#51]
VSC Version: 1.31.1

the first line of `keybindings.json`(user defined key binding, not default one) has a translation error.

> 将密钥绑定放在此文件中以覆盖默认值

should be:

> 将键绑定放在此文件中以覆盖默认值

![image](https://user-images.githubusercontent.com/24759802/53677114-cada6b00-3ce5-11e9-972e-121a6c2961f2.png)

**Comment by shawndon** [comment]
Assigning to Loc production to address.

**Comment by lukaschal** [comment]
CHS. On review.

SRC: Place your key bindings in this file to override the defaults
TGT: 将密钥绑定放在此文件中以覆盖默认值

**Comment by lukaschal** [comment]
Fixed.

New TGT: 将键绑定放在此文件中以覆盖默认值

**Comment by shawndon** [comment]
@imba-tjd Fixed
