### ISSUE TITLE
Make a punctuation guideline

### ISSUE THREAD

**Issue by wangweixuan** [microsoft/Localization#52]
I am using the Chinese (Simplified) Language Pack for Visual Studio Code and I am feeling unsatisfied about its translation, particularly its use of punctuation. Different halfwidth and fullwidth quotation marks `' '` `" "` `“ ”` and parentheses `( )` `（ ）` are used interchangeably everywhere.
Another significant problem is whether a space should be inserted between Latin and Chinese characters, or between digits and Chinese characters. Normally we would have the space for readability, but exceptions to this convention are also found in the strings.

The above problems have become widespread and I believe something must be done to stop further confusion from appearing.
The previous issue #19 has suggested that the punctuations should show respect for the target language, but currently it's pretty hard for new translators to discover that information, as it is not documented in our wiki. Additionally, the machine translation seems to always give halfwidth punctuations, which also leads to inconsistencies.

Therefore I believe we need to publish a clear guideline on punctuation, and possibly put up a notice in landing pages to the localization project, so that translators can learn to use the preferred punctuation. The guideline may be rather brief, just like the [coding guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines), as long as we can actually clarify what is expected.
Meanwhile the current translations should undergo a cleanup. Ideally it's just a replace of punctuations, but the project would be too huge for individual contributors to carry out.

**Comment by shawndon** [comment]
@wangweixuan Thanks for the feedback. Our linguistic team will take a look at the quality. Do you have any examples? Also, I will look into providing better writing style guidelines.
