### ISSUE TITLE
Korean translation error found in vscode

### ISSUE THREAD

**Issue by Epikem** [microsoft/Localization#57]
It shows '실행중인 저장 관계자...' when i save a file but it is wrong because it means 'the executing save manager' but i can't find the string on MLCP site. It should be at least like '저장 관계자 실행중...' which means 'executing save manager...' or could be just '저장중...' which means 'saving...'

**Comment by terrysheng** [comment]
@danyeh Could you please have a look of this MLCP feedback for Korean?

**Comment by terrysheng** [comment]
@Epikem Thanks so much for your valuable feedback. I will work with the teams to check and update it. Thanks so much.

**Comment by lukaschal** [comment]
On review.

SRC: Running Save Participants...
TGT: 실행중인 저장 관계자...

**Comment by lukaschal** [comment]
Linguistic answer: Current target is not accurate and confusing. For the source "Running Save Participants..." I suggest the new translation as: 참가자 저장 실행 중... which means "Running the save of participants".

New TGT: 참가자 저장 실행 중...

**Comment by Epikem** [comment]
I misread 관계자(Participants) as 관리자(Manager), Participants - 관계자 is right. The source sentence was confusing to me but I understood its meaning after reading this: https://github.com/Microsoft/vscode/issues/50351. So it means running extensions which related to save, not documents to save. Then '저장 관계자 실행중...' or '저장 참가자 실행 중...' would be correct. or '저장 처리자 실행중' which means 'running save processors' but this is a little different from source.

**Comment by terrysheng** [comment]
Thanks so much @Epikem 
Hi @lukaschal , could you please check with Linguistic Expert's opinion regarding @Epikem 's suggestion? (although it might be a little different from source)
Thanks

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

new tgt: 저장 관계자 실행 중...
