### ISSUE TITLE
My account is duplicated in the leaderboard

### ISSUE THREAD

**Issue by momoto** [microsoft/Localization#58]
My account appears duplicated in the leaderboard. My accounts are shown up as:

- Momoto, Seiji
- Seiji Momoto

**Screenshot:**

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/836856/57176966-eacf0c00-6e99-11e9-8e95-fb051e8a6026.png">

I guess that **Momoto, Seiji** is recognized as contributing from [my GitHub account](https://github.com/momoto) and that **Seiji Momoto** is from MLCP. I signed up for MLCP with [my Outlook.com account](mailto:seiji.momoto@outlook.com). Could you please let me know if you need any further information?

Thanks,

**Comment by shrijap** [comment]
Thank you for reaching out to us. We are looking into this, and will update you as soon as this is fixed. We appreciate your feedback!

**Comment by shrijap** [comment]
This issue has been fixed now. Thank you again! Please let us know if there are any other concerns.
