### ISSUE TITLE
Request for Telugu( te-IN) 

### ISSUE THREAD

**Issue by deepaktatineni** [microsoft/Localization#59]

**Comment by aldonetti** [comment]
thank you for your interest and willingness to contribute @deepaktatineni - we need to get a few users to make such requests for the same language, because if there is not enough commitment/interest from a few contributors, it will never get translated.
@danyeh could you please add this to the count of requests? 
thanks!

**Comment by aldonetti** [comment]
hi again @deepaktatineni - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project). 
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by satyamkondle** [comment]
Hi @aldonetti, I would also like to request to include Telugu. I am willing to contribute to this effort. Thank you.

**Comment by vpinnaka** [comment]
Hi @aldonetti and @satyamkondle, I am willing to contribute to include Telugu, please let me how I can help

**Comment by deepaktatineni** [comment]
and then there are three

**Comment by aldonetti** [comment]
thank you all! I have update the count on the VSCode page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project#list-of-languages-requested--number-of-requests). Let's see if we can get a few more ...
thanks!!

**Comment by masthandev** [comment]
hi i would like to add telugu language and i am willing to contribute please let me know any help required

**Comment by Chandu3245** [comment]
Hi There,  @aldonetti and @satyamkondle, I am willing to contribute to include Telugu, plz let me know how can I help.

**Comment by aldonetti** [comment]
thank you @masthandev and @Chandu3245 - I have added you both to the count. and we have 5 now, so we can enable it. it may take a bit of time as other engineering changes are being deployed and we have a couple of other languages to enable before Telugu but we will get there. Please bear with us for a bit longer.
And if you can any other to sign up in the meantime ... the more the better!
Thanks!
Aldo

**Comment by aldonetti** [comment]
thank you @mastercoder8 ! I've added you to the count. As soon as we enable contributions we will let you know here, so make sure to keep an eye on this thread 👍

**Comment by harifutures** [comment]
Hi @aldonetti, willing to contribute for te-IN, let me know of any help!

**Comment by kranthilakum** [comment]
Hi @aldonetti, I am interested to contribute. Please add me to the count.

**Comment by gvsakhil** [comment]
Hi @aldonetti , I am interested to contribute, add me

**Comment by hemanthkk** [comment]
Hello @aldonetti , I am willing to contribute for Telugu language support, please add me also.

**Comment by movva30** [comment]
I am willing to contribute for Telugu language support

**Comment by prem30** [comment]
I am willing to contribute for Telugu language support

**Comment by pramodkrishnaV** [comment]
Hi, I would also request to include Telugu. I am willing to contribute to this effort. Thank you all.

**Comment by rkdhanyakula** [comment]
Hi, I would also request to include Telugu. I am willing to this.
TQ

**Comment by tchkreddy** [comment]
Hi @aldonetti, I'm willing to contribute for te-IN
