### ISSUE TITLE
How can I contribute to localize docs.microsoft.com pages which have no "edit" link?

### ISSUE THREAD

**Issue by anikundesu** [Microsoft/Localization#6]
I read the wiki https://github.com/Microsoft/Localization/wiki/Contribute-to-docs.microsoft.com and then looked some pages I want to translate into Japanese.
However, the pages have no "edit" link on top of the page. For examples, "https://docs.microsoft.com/ja-jp/virtualization/windowscontainers/about/" has no "edit" link.

How can I contribute to translate such pages?

**Comment by Sara-Nicolini** [comment]
Hi Takashi-san, thanks for your inquiry. Currently, most of the content related to Cloud and Enteprise products is enabled for community contributions, such as Azure, Visual Studio, SQL, ASP.NET Core, System Center, Intune, etc. However, most of the Windows content is not enabled for community contributions at the moment. We will inform you once this content becomes available to be edited.
