### ISSUE TITLE
Request for Slovak (sk-SK) localization

### ISSUE THREAD

**Issue by felsocim** [microsoft/Localization#60]
As an active developer originated from Slovakia, I would like to contribute to the Slovak localization of VS Code!

**Comment by anceque** [comment]
I also would like to contribute to the localization. Can sk-SK be added?

**Comment by aldonetti** [comment]
thank you for your interest and willingness to contribute @felsocim and @anceque! It's great to get 2 requests in one :)  We need to get a few users to make such requests for the same language, because if there is not enough commitment/interest from a few contributors, it will never get translated.
@danyeh could you please add this to the count of requests?
thanks!

**Comment by aldonetti** [comment]
hi again @felsocim and @anceque  - i have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) . 
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by Bilosista** [comment]
Hi guys. If possible, I'd also like to contribute. My mom is using VSCode for editing HTML and JSON files and it would be great if she could understand everything VSCode "tells" her :)

**Comment by MaekToth** [comment]
Hi, guys, I want to contribute, too!

**Comment by aldonetti** [comment]
thank you @Bilosista and @MaekToth - I have recorded your requests by incrementing the counter in the VSCode project page. Hopefully as we get a couple more contributors, we could then enable it

**Comment by Burarrum** [comment]
Hey guys, I can contribute as well.

**Comment by brano-p** [comment]
Hello, nice to see the number increasing. Please add me as a contributor, too!
