### ISSUE TITLE
Request for Malayalam( ml-IN)

### ISSUE THREAD

**Issue by shabeerkdm** [microsoft/Localization#62]
Kindly add Malayalam language option in MS Localization Community.

**Comment by aldonetti** [comment]
thank you for your interest and willingness to contribute @shabeerkdm - we need to get a few users to make such requests for the same language, because if there is not enough commitment/interest from a few contributors, it will never get translated.
if you happen to know other from your community who are willing to contribute please ask them to reply to this message, so we can count them
@danyeh could you please add this to the count of requests?
thanks!

**Comment by aldonetti** [comment]
hi again @shabeerkdm  - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) . 
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by jithinjohne** [comment]
Hi Can you please add malayalam to visual studio code? I can contribute.

**Comment by aldonetti** [comment]
that's great, thank you @jithinjohne - I have incremented the counter at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project). As soon as we get to at least 4/5 we'll reevaluate/enable it. It's already hard with those many people involved.
thanks!

**Comment by somzJosf** [comment]
I can contribute to this.

**Comment by paulkiren** [comment]
I can contribute to this.

**Comment by aldonetti** [comment]
thank you all! I have updated the counter at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project#list-of-languages-requested--number-of-requests). Let's see if we can get a few more ...
thanks!!

**Comment by amathew-statestreet-com** [comment]
I can contribute to this.

**Comment by aldonetti** [comment]
thank you @amathew-statestreet-com - as we now have 5 potential contributors we will start discussing it to se if/when it can be enabled. Hopefully in the meantime more will join ...
thanks!

**Comment by paulkiren** [comment]
We need Malayalam in the language section.

**Comment by ebbypeter** [comment]
I can contribute to the Malayalam localization of VSCode.

**Comment by nidhinp** [comment]
I can contribute to Malayalam localization

**Comment by anupjon** [comment]
I can contribute.

**Comment by ebinxavier** [comment]
Please add Malayalam, I am ready to contribute.

**Comment by josephmachine** [comment]
Pls add malayalam. Interesting. I have just started using this and will be glad to be part of the team. will contribute as I can. All the best.
