### ISSUE TITLE
Request for Bengali Language Support

### ISSUE THREAD

**Issue by blindfirefly16** [microsoft/Localization#63]
It would be great for the Bengali Community to have visual studio code in Bengali Language. We want Visual Studio Code to be that kind of global. We, the Bengali Community, are eagerly waiting to start contributing to vs code as soon as it supports our language.

**Comment by aldonetti** [comment]
thank you for your interest and willingness to contribute @blindfirefly16 - we need to get a few users to make such requests for the same language, because if there is not enough commitment/interest from a few contributors, it will never get translated.
If you know you can "enroll" a few more contributors, please do, and have them reply to this message as a "me too" :)
@danyeh could you please add this to the count of requests?
thanks!

**Comment by aldonetti** [comment]
hi again @blindfirefly16  - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) . 
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by amit-viacon** [comment]
Please enable Bengali language support. There are currently 260 million speakers and I would love to contribute.

**Comment by amit-viacon** [comment]
Please enable Bengali language. There are currently 260 million speakers and I would love to contribute.

**Comment by aldonetti** [comment]
thank you for your interest @amit-viacon ! 
I have added your request in the [VSCode project page](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) and have also added a reference to this thread to make it easier for others to find this thread.
As soon as we get to 4/5 volunteers we can enable it.
thanks again,
Aldo

**Comment by fahimshahrierrasel** [comment]
Enable it I hope we can manage more than 4/5 people to contribute on Bengali language pack

**Comment by ahashan-LS** [comment]
Please enable it. You will find plenty of volunteers.

**Comment by mohammadraasel** [comment]
It will be really great. So, Please enable it

**Comment by shubhamviacon** [comment]
Please enable Bengali language. I would love to contribute. It will be really great for our community. please please please please enable Bengali language.

**Comment by nurulhuda859** [comment]
me too

**Comment by aldonetti** [comment]
thank you all for your interest! looks like we have a quorum :)
I'll reply to this thread shortly with more info
thanks!

**Comment by dreygur** [comment]
Please enable Bangla Language. I am ready to support.

**Comment by blindfirefly16** [comment]
@aldonetti... Can we change the Culture ID from bn-IN to bn-BD Please.

**Comment by aldonetti** [comment]
@brunolewin-msft can you please confirm which one is the correct default Culture ID for the Bengali language "bn" ? Thanks! (I know, but I'd like your expert opinion :) )

**Comment by brunolewin-msft** [comment]
@aldonetti - we generally try hard to avoid picking a specific "default" coutry/region for a given language and try hard to keep things neutral wherever possible to be respectful of the multiple communities who use very close variations of a given language. E.g. in Azure, we have one German (de) version that works in the many German-speaking regions where we have users when it comes to picking a language (though we do default to German-Germany for date/time formating, but user can easily change that).

Let me check if there is some technical constrains that really forces us to pick a default for VSCode and get back...

**Comment by weeteckt** [comment]
Thanks for all the input. The language will not be associated to a specific country/region and therefore CultureID reference will be removed. We will also update the MLCP Language code to Bengali(bn).

**Comment by aldonetti** [comment]
thank's great - thanks for the input and action @brunolewin-msft and @weeteckt !

**Comment by aldonetti** [comment]
hi everyone - I just wanted to let you know that while in the process of enabling Bengali we realized that that language is missing from the backend and requires an engineering change - due to previously committed work the engineering team cannot commit to implementing that until the end of July. (thanks @weeteckt for pushing and tracking that) we'll update you once we are done. thanks!

**Comment by blindfirefly16** [comment]
Thanks for the update. We are waiting till the backend work gets done. In the meantime we will try to engage more volunteers in this project. Thanks again!

**Comment by sibber11** [comment]
I am in.

**Comment by aldonetti** [comment]
great! thank you @sibber11 . this should be available shortly.

**Comment by sibber11** [comment]
any good news??

**Comment by aldonetti** [comment]
Hi @sibber11 some good news in general but not specifically for the Bengali community - the engineering team is currently working on improving the MLCP platform overall by addressing some of the top asks, and that's going to take about another month or so before the Bengali language is enabled. All, please bear with us until these improvements are deployed and we can then tackle the enablement of Bengali. Hopefully these changes will benefit everyone. I will update this thread again as soon as Bengali is enabled. Thanks again for your patience! /cc @weeteckt

**Comment by dreygur** [comment]
Thanks @aldonetti  :smile:

**Comment by fwpushan** [comment]
Want to contribute for Bengali Language support. Really appreciate this and overall initiative. :)

**Comment by aldonetti** [comment]
thank you @fwpushan - hopefully it's not going to be long before we can enable it. @weeteckt or I will keep you posted. thanks!

**Comment by mayeenulislam** [comment]
Request from @blindfirefly16 is appreciated. :100:  I'm one of the GTEs of `bn_BD` in WordPress Translations. Please count me in too. Would love to contribute to VSCode as well.
Waiting for the MLCP platform update so that we can start fresh.

**Comment by code4ash** [comment]
I am also interested to contribute. Let's hope for the best.

**Comment by satyaki1** [comment]
I'm interested to contribute. Please help me to know, how to contribute. Thanks.

**Comment by dreygur** [comment]
Any news? @aldonetti

**Comment by sibber11** [comment]
We were expecting something from you @aldonetti @weeteckt

**Comment by rajibahmed** [comment]
Hello beautiful nice people of vscode community. I would like contribute to Bengali localization too. And if need I can contribute to some beginner stuff too :)

**Comment by rafee** [comment]
I want to express interest in Bengali localization.

**Comment by rokonxr** [comment]
Any Update ?

**Comment by sibber11** [comment]
@aldonetti @weeteckt Any news?

**Comment by mhmithu** [comment]
Interested to be a part of Bengali localization. Eagerly waiting.

**Comment by raiyankamal** [comment]
Hello, I would like to contribute in BN localization. 
As I understand, some back end development has to be completed first before we can start contributing. In the meantime, would it be possible to get hold of a string table or something of the sort? So that interested people can start accumulating translations in an unofficial repo?
@aldonetti @weeteckt can you please advise? Thanks a lot.

**Comment by aldonetti** [comment]
thank you all for your interest! I'll let @shrijap comment/advise on this, as MS is currently replacing  the tool overall (front and backend)

**Comment by meataur** [comment]
I am interested too. Please count me in. Thanks.

**Comment by sibber11** [comment]
is this thread is abandoned?

**Comment by tariqulislam16** [comment]
**@sibber11** Let's hope it's not the case. As **@aldonetti** said, they have been through major changes. I hope MS Team won't ignore the presence of such a big community.

**Comment by aldonetti** [comment]
hello @sibber11 and @tariqulislam16 - I will let @ericvt comment or delegate to someone appropriate. thanks!
