### ISSUE TITLE
Microsoft Cloud + AI International Community Leaderboard is ....

### ISSUE THREAD

**Issue by JungYeolYang** [microsoft/Localization#65]
Microsoft Cloud + AI International Community Leaderboard score tabe is same as Microsoft Cloud + AI International MVP Leaderboard score table.

**Comment by JungYeolYang** [comment]
Um... It's not same as Microsoft Cloud + AI International MVP Leaderboard score table.  Anyway Thanos did something weired. There is not my score :'(

**Comment by aldonetti** [comment]
hi @JungYeolYang - sorry to hear you cannot find your score. Was it there before? (you know there's a minimum of 100 points to appear on the Leaderboard)
if so, can you please let us know your info and we can check? You can find how to reach out to us at the bottom of the leaderboard page (email or web form)
thanks!

**Comment by shrijap** [comment]
Hi @JungYeolYang - We are fixing this now and you should be able to see your score again in about 24 hours. Thank you for your patience as we fix this, and appreciate you reaching out to us through all the proper channels!
