### ISSUE TITLE
Microsoft Cloud + AI International Community Leaderboard is not working now!

### ISSUE THREAD

**Issue by JungYeolYang** [microsoft/Localization#66]
Point calculation is not working recently. Please check it out.

**Comment by shrijap** [comment]
Hi David. Could you tell us what is missing? Also, we have disabled points for any contributions made to  Machine Translated topics on Microsoft Docs currently. So if you do not see your points updated after contributing to an MT topic, then this is the reason. However, if it is something else, then please give me more details. Thank you!

**Comment by JungYeolYang** [comment]
Hi shrijap. So I wanna know how to get the points posted the Microsoft Cloud + AI International Community Leaderboard. A few days ago, I could get the points with MT topic, but now I can't get the point with this way.

**Comment by aldonetti** [comment]
Hi @JungYeolYang - the description of how points in the Leaderboard are calculated, is just at the bottom of the [Leaderboard page](https://microsoftl10n.github.io). In summary, 2 ways: by contributing to the translation of selected Open Source Projects (see the [main wiki page](https://github.com/Microsoft/Localization/wiki)) *or* a Pull Request that suggests an improvement/fix on a Docs article (but now only on Human Translated articles, not Machine Translated ones - temporarily - see announcement [here](https://github.com/Microsoft/Localization/wiki#-news--events)).
I you have any other question please do let us know.
thank you!
