### ISSUE TITLE
Enable Arabic in MLCP

### ISSUE THREAD

**Issue by omaraljumaili** [microsoft/Localization#67]
I do have a passion for the Arabic language and commit to contributing to the translation of Arabic and enable it in MLCP.

**Comment by aldonetti** [comment]
thank you for interest and willingness to contribute @omaraljumaili !
while there is no problem adding Arabic to MLCP, if you mean to contribute to the Arabic translation of VSCode, there is unfortunately a product limitation which does not allow it to be translated into any Right-To-Left or Bidirectional language, so Arabic is not supported.
Sorry about that.
thanks!
