### ISSUE TITLE
Urdu localizations error

### ISSUE THREAD

**Issue by ZtheLeader** [microsoft/Localization#68]
I am into Urdu translation for VS Code. After following the steps for registration for "Initial platform sign up", I am brought to "Microsoft Localization Community platform". But here I see nothing. Projects dropdown has no options and data below shows nothing too.

Can Anyone help me here ?

**Comment by aldonetti** [comment]
hi @ZtheLeader , thank you for your interest in the translation of VSCode !
As explained in a [similar request](https://github.com/microsoft/Localization/issues/67) there is unfortunately a product limitation which does not allow it to be translated into any Right-To-Left or Bidirectional language, so Urdu is not supported.
Sorry about that.
thanks!
