### ISSUE TITLE
Please add Arabic Egypt (ar-eg) or just Arabic (ar) language to MLCP 

### ISSUE THREAD

**Issue by AhmedShaikoun** [microsoft/Localization#69]
Can you please add Arabic Egypt (ar-eg) or just Arabic (ar) language to MLCP, it will be a good addition and the most users of vs code in Arabic is Egyption developers

**Comment by aldonetti** [comment]
@AhmedShaikoun - thank you very much for your interest and willingness to contribute, Ahmed! 
As mentioned in this Issue [67](https://github.com/microsoft/Localization/issues/67), unfortunately VSCode has an engineering limitation for which Right-To-Left/BiDirectional languages like Arabic or Urdu are not supported. I'm sorry about that.
However, I am recording the requests in this [page](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) and will check again with the engineering team if there's been any progress on that front.
/cc @weeteckt
