### ISSUE TITLE
Update to the latest icon color

### ISSUE THREAD

**Issue by egamma** [Microsoft/Localization#7]
A nit, but the icon color has evolved 😄 

![image](https://user-images.githubusercontent.com/172399/34292456-4cb7b646-e701-11e7-93d1-f3769e1f808c.png)

**Comment by aldonetti** [comment]
thanks, will fix it asap

**Comment by aldonetti** [comment]
not an artist but this should be the correct one now - check [VSCode wiki page](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project)

**Comment by egamma** [comment]
Looks good 👍 , thanks
