### ISSUE TITLE
Microsoft Cloud + AI International Community Leaderboard issue report

### ISSUE THREAD

**Issue by JungYeolYang** [microsoft/Localization#72]
Hello. I’m David Yang. 
I wanna know how the two persons(the red boxes in the image) to got their score tooooooo quick! 
I mean the calculation system has some problems…
Please check the two person's pull requests and score..
Thx in advance.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/13944439/61173283-415c7300-a5cc-11e9-9037-16db82eea9b1.png">

**Comment by aldonetti** [comment]
Hi @shrijap can you please check? Thanks

**Comment by JungYeolYang** [comment]
Yoichi Nakamura either!

**Comment by shrijapPERSONAL** [comment]
Hi @JungYeolYang - we will look into this and let you know soon. Thank you for your feedback!

**Comment by shrijap** [comment]
Hi @JungYeolYang - we are looking into this and will update you soon. Thank you for your feedback!

**Comment by shrijap** [comment]
Hi @JungYeolYang - thank you for bringing this to our attention. This was a data refresh issue and has now been fixed. Thank you for your valuable feedback again!
