### ISSUE TITLE
VSCode fr-Fr translation error "Problème d'aperçu"

### ISSUE THREAD

**Issue by bastien-boussouf** [microsoft/Localization#73]
In Visual Studio Code, when a linter flags a line with an issue, the editor can show an overlay with quick fix and preview links.

The current fr-Fr translation for the preview link seems wrong as it reads "Problème d'aperçu" instead of "Aperçu du problème". The former has a totally different meaning and implies there is a problem with the preview itself while the latter invites to get a preview of the problem.

![image](https://user-images.githubusercontent.com/29279482/62049595-db006300-b20f-11e9-894a-e47d4502b76d.png)

**Comment by aldonetti** [comment]
thank you @bastien-boussouf ! @weeteckt can we see where is this string located please? thanks!

**Comment by weeteckt** [comment]
We are implementing the fix and will target to include this in the next language pack version.

**Comment by johnliu2016** [comment]
The fix is implemented into community localization platform (MLCP)

**Comment by johnliu2016** [comment]
new Language Packs for VSCode containing the fix is published
