### ISSUE TITLE
请问为什么要把 "funcation" 翻译为 ”功能“？

### ISSUE THREAD

**Issue by mrchar** [microsoft/Localization#74]
我是用VSCode并安装了Go插件进行golang开发，在大纲视图中，function 被翻译为 功能，请问为什么不使用程序员更熟悉的函数这个词？
![function](https://user-images.githubusercontent.com/51408183/62602228-db8ead00-b925-11e9-8081-e17b38157537.jpg)

**Comment by aldonetti** [comment]
seems like a disconnect between the translation in the window and in the tooltip /cc @weeteckt

**Comment by weeteckt** [comment]
@janbaltus, could you check which is more appropriate in this context, the current translation 功能 or 函数 as suggested?

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested. Translation changed from 功能 to 函数.

**Comment by mrchar** [comment]
更新插件看到已经将“功能”替换为“函数”， 非常感谢！
