### ISSUE TITLE
Adding Catalan to MLCP

### ISSUE THREAD

**Issue by svcabre** [microsoft/Localization#75]
I would like to help to translate Visual Studio Code into Catalan Language. However, I couldn't find it in the options for Microsoft Localization Community. Would it be possible to add it in?

**Comment by aldonetti** [comment]
hi @svcabre - thank you for your interest and willingness to help - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by aseques** [comment]
@aldonetti where should we add as a volunteers for the catalan translation? I'll would like to join

**Comment by aldonetti** [comment]
hi @aseques and thank you for your interest. as more people reply to this thread I will increment the counter at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project)
Thanks!

**Comment by fitojb** [comment]
Count me in!

**Comment by xnaval** [comment]
Count with me too.

**Comment by svcabre** [comment]
> hi @svcabre - thank you for your interest and willingness to help - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
> I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
> Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
> thanks! Aldo

Hi Aldonetti,

We already reached 5 people to start doing the Catalan translation of Visual Studio Code. Do you think it will be possible to open it and if you can share how we can proceed to start working on this?

Thank you,

Sergi,

**Comment by aldonetti** [comment]
thank you Sergi @svcabre - to enable it, we first need some engineering changes to be deployed to the translation tool (MLCP) which are currently blocked. We are working to unblock those and then we will move forward enabling some languages. Those with the highest number of requestors first and see how they go. Currently the list is [this](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project#list-of-languages-requested--number-of-requests), and the language which will be enabled first is Bengali. Other languages to follow
Thanks!!

**Comment by aldonetti** [comment]
Hi @svcabre absolutely! thanks!

**Comment by festuc** [comment]
I can help to translate VS Code to Catalan :)

**Comment by festuc** [comment]
I can help translate VS Code to Catalan :)

**Comment by mplaaguilera** [comment]
hi there, I would be fully comitted to help with the Catalan translation. Please add my request, thank you. btw, thanks too for building such an amazing IDE. :)

**Comment by burguitoscat** [comment]
Hi! I can help translate VS Code to Catalan, my mother language!

**Comment by corretge** [comment]
Hi @aldonetti , now that we are confined by COVID19 it's more easy to dedicate resources to the translations.

Could the team enable the Catalan translation? If you think that we are not enough requesters, we can start a campaign ;)

Lots of thanks.

**Comment by svcabre** [comment]
Hi @aldonetti, I was reviewing the number of volunteers that want to collaborate with translating Visual Studio code and your counter Says 5 volunteers but in this thread I am counting 7:
@svcabre, @aseques, @fitojb, @corretge, @xnaval, @mplaaguilera, @burguitoscat.

![image](https://user-images.githubusercontent.com/14053222/78927317-931c2600-7a96-11ea-97b2-a2b93cd51cb5.png)
  
Also the locale should not be like this?  **ca-ES** To avoid collision with Georgian language?

Thanks,

**Comment by helderdcarvalho** [comment]
Hi @aldonetti, I can help to translate Visual Studio Code to Catalan.

**Comment by aldonetti** [comment]
Hi everyone, thanks a lot for your interest! As you can [read](https://github.com/Microsoft/Localization/wiki#-news--events) the platform is being replaced with a more robust and modern one, so all languages are in stand by for a bit. please let @shrijap know (or send email as per the news article) if you have any feedback/concern. thanks!!
