### ISSUE TITLE
Adding “Nepali (Nepal)” (ne_NP) to MLCP

### ISSUE THREAD

**Issue by aayulogic** [microsoft/Localization#76]
I and my team are too much eager to contribute to MLCP for Nepali Language. Please enable it.

**Comment by aldonetti** [comment]
hi @aayulogic - thank you for your interest and willingness to help - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo

**Comment by bsomhz** [comment]
We would like to contribute MLCP for Nepali Language. Please enable it.

**Comment by aldonetti** [comment]
thank you @bsomhz - I've added you to the count on [this page](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project)

**Comment by anuragregmi** [comment]
We would also love to contribute to MLCP for Nepali Language.

**Comment by adhikariravi** [comment]
I am also willing to contribute to this project. Please consider it.

**Comment by ManSth** [comment]
I am also eager to contribute in this Project.

**Comment by bcpratik** [comment]
We are seeking an opportunity to contribute MLCP for Nepali Language. It would be great if you enable it for us.

**Comment by aldonetti** [comment]
thank you all! I have updated the count on the page mentioned above.
it really seems there are few volunteers now - we are waiting for some engineering changes to be deployed to MLCP in the upcoming weeks, then we have another language to enable first. Then we'll tackle Nepali. Please bear with us for a bit longer ....
thank you!
Aldo

**Comment by ikushum** [comment]
Please make it happen. Eagerly waiting. :)

**Comment by ankitshrestha** [comment]
I am eagerly waiting to contribute MLCP for Nepali Language. People of Nepal would greatly appreciate 
 if its enabled.

**Comment by Ramesh47** [comment]
I am also interested to contribute to MLCP for Nepali Language.

**Comment by mausamshresthabv** [comment]
I would like to contribute as well. This would be a big milestone. Thanks VSCode team!

**Comment by themausam** [comment]
I would like to contribute as well. This would be a big milestone. Thanks VSCode team!

**Comment by sushil79g** [comment]
Please make it happen.

**Comment by bipin-lekhak** [comment]
Any updates on this? 
Willing to contribute.

**Comment by samundra** [comment]
I am also interested to contribute for localization of Nepali language in Visual studio code. Please enable it.
