### ISSUE TITLE
Japanese translation error in VSCode

### ISSUE THREAD

**Issue by noriokaki** [microsoft/Localization#77]
Translations of Git related messages are missing.   

![image](https://user-images.githubusercontent.com/12603061/63325127-7e9ee800-c364-11e9-8de4-12d49862e32d.png)

![image](https://user-images.githubusercontent.com/12603061/63325201-a55d1e80-c364-11e9-87fd-81b788d20348.png)

![image](https://user-images.githubusercontent.com/12603061/63326392-18679480-c367-11e9-8400-cef90cdfecbf.png)

**Comment by lukaschal** [comment]
@weeteckt Are these strings exposed to localization ?

https://devdiv.visualstudio.com/Personal/_git/andarno.vscode?path=%2Fextensions%2Fgit%2Fsrc%2Fcommands.ts&version=GBremote-hackathon

**Comment by janbaltus** [comment]
@weeteckt between resources we have for Vscode above strings are not present.
Maybe question for Dirk whether we want to localize this repo/extension?

**Comment by lukaschal** [comment]
@noriokaki Hi, could you please provide us more info about tested build (drop location, install location, branch etc.)?

**Comment by noriokaki** [comment]
@lukaschal 
vscode info
version: 1.37.1 (user setup)
commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Japanese Language Pack for Visual Studio Code ver.1.37.5
drop location :https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja
install location: vscode default

**Comment by janbaltus** [comment]
String location https://github.com/microsoft/vscode/blob/master/extensions/git/src/commands.ts

**Comment by dbaeumer** [comment]
@janbaltus I ran the export script and can reproduce this. Actually all extensions are basically broken in this respect. I will look into this together with @joaomoreno. We changed something how extensions are compiled when they are web packed.

**Comment by noriokaki** [comment]
This probrem was fixed in Ver.1.38.4.
Thanks!
