### ISSUE TITLE
Add Telugu for Localization

### ISSUE THREAD

**Issue by HemanthPaluri** [microsoft/Localization#79]
Hi Team,

Can you please add Telugu for Localization I would love to contribute.

Thanks

**Comment by aldonetti** [comment]
Thank you very much for your interest @HemanthPaluri - there is already a request for Telugu on #59 so I am closing this, but I have added your name into the count of volunteers on the VSCode page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project)
I will let you know when it's enabled
thank you!
Aldo
