### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by severinolorillajr** [Microsoft/Localization#8]
I'd like to contribute translations to Filipino. 
Do we have someone who can check the accuracy of the translation?
I have made some readings.
https://github.com/Microsoft/Localization/wiki/Contribute-to-docs.microsoft.com
Are there other things that I need to be aware of before I start?

**Comment by aldonetti** [comment]
Hi @severinolorillajr - thank you for your interest and willingness to help.
Unfortunately users cannot translate a full article on their own - they can only contribute to existing articles.
You know how much documentation there is, so it's almost impossible that individual contributors can keep up with translating all of that on their own (both for first translation and for updates over time) - that is why we discourage it. 
However, if you find any error in the existing documentation (in English or other languages you may know) please feel free to follow the process indicated in the article above.
thank you!
