### ISSUE TITLE
Add Macedonian for Localization

### ISSUE THREAD

**Issue by isakfi** [microsoft/Localization#81]
Hello!

Please add the Macedonian language to the Localization Community platform.

Thank you.

**Comment by aldonetti** [comment]
Hello @isakfi  - thank you for your interest and willingness to help - I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. There are about 85000 words to be translated in VSCode today and it's no small task - even with 5/6 people committed it is still a big task. You can see in the [dashboard](https://microsoftl10n.github.io/VSCode.html) how many languages were started but are not even close to being 50% done ... and we have 4/5 people committed.
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!
thanks! Aldo
