### ISSUE TITLE
create a new language pack for Kannada language

### ISSUE THREAD

**Issue by Shashidharankrish** [microsoft/Localization#83]
I want to create a new language pack for Kannada Language. or is there any team working on it?
I will be glad to work on it.

**Comment by aldonetti** [comment]
Thank you for your interest and willingness to help your local community @Shashidharankrish 
I am going to add Kannada in the list of languages to expand VSCode into, on [this page](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) in the hope that we will get more contributors going forward.
As mentioned in other requests (e.g. #75 ) it's no small effort, so we need to get a few committed volunteers before we enable it
But thanks for starting the thread - I'm closing it for now until more people join
thanks
Aldo

**Comment by amarnit** [comment]
Hi @aldonetti, I'd like to contribute to this.
@Shashidharankrish - thanks for starting this thread!

**Comment by xaisng** [comment]
Count me on.. In for Kannada Translation.

**Comment by santhushine** [comment]
I'm interested in for Kannada language pack..
