### ISSUE TITLE
Leaderboard issue

### ISSUE THREAD

**Issue by hongju** [microsoft/Localization#84]
The MVP Leaderboard is daily updated but the Community Leaderboard is not updated(Sep 4)

please revalidate score and daily data refresh.

**Comment by aldonetti** [comment]
thank you @hongju - @shrijap could you please check? thanks!

**Comment by shrijap** [comment]
@hongju thank you for bringing this to our attention. The report has been refreshed now.

**Comment by echoix** [comment]
How come the leaderboard is still only refreshed on Sept 19, 10:40 AM (PST). Shouldn't the PowerBI visualization be configured to be updated daily?

**Comment by aldonetti** [comment]
@shrijap

**Comment by shrijap** [comment]
Hi @echoix 
Thank you for bringing this up. It seems the automatic refresh had turned off somehow. It's refreshed and going to be on a daily refresh. 

We truly value your feedback!

**Comment by echoix** [comment]
@shrijap Should it be updated and corrected now?

On a phone I can’t use the search bar to look for a specific person too. But it still shows that it was last updated in September.
![32E292B8-97FC-4843-B9CB-59EE8857194E](https://user-images.githubusercontent.com/27212526/68612344-523dc800-048a-11ea-9e56-743cb8fce242.png)

**Comment by shrijap** [comment]
Hi @echoix. There may have been a delay in the website refresh. It should be showing as refreshed on November 11th now. 

As of now, the visuals are fully compatible with the desktop version of the site only.

**Comment by hongju** [comment]
Are the scores reliable? 
Several people's score downed.

**Comment by shrijap** [comment]
@hongju apologies for the delayed response. The scores should be reliable, we might have had some data issues earlier which was allowing points to be given for MT contributions. Scores should be final.
