### ISSUE TITLE
Create a new Language pack

### ISSUE THREAD

**Issue by TibebeJS** [microsoft/Localization#85]
Looks like there is no አማርኛ(amharic) language pack yet. I would like to help contribute in creating one. Thanks.

**Comment by TibebeJS** [comment]
It is a language spoken in Ethiopia, Eritrea.

**Comment by aldonetti** [comment]
thank you @TibebeJS for you interest and willingness to support your community by enabling the Amharic language. As mentioned for other languages (eg. see #75) it is a big task to translate VSCode, as there are more than 85 thousand words. So even with 5/6 contributors it is going to be challenging.
I have recorded your request at the bottom of the VSCode project page [here](https://github.com/microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project).
I'm closing this issue for now, until we get more requests from people willing to contribute, like you. 
Thank you for your interest and please feel free to engage others - we'd love to have new languages available for the benefit of the local communities!

Thanks, 
Aldo

**Comment by ismaelkedir** [comment]
Me and many other friends and collegues are willing to contribute to our favourite editor. Please help us enable the Amharic language.
