### ISSUE TITLE
Microsoft Cloud + AI International Community Leaderboard issue report

### ISSUE THREAD

**Issue by changeworld** [microsoft/Localization#86]
Hello, I'm Takashi Takebayashi.
I wanna know how the two persons (SONG WONSEOK and Takashi Takebayashi) to got their score too quick!
I (Takashi Takebayashi) sent nearly 10,000 pull requests to a Microsoft repository.
However, the calculation system calculates that I sent nearly 50,000 pull requests.
From the issue of #72, it seems to me that there is an error in the calculation logic.
Please check the calculation logic of the calculation system.
Thx in advance.

**Comment by terrysheng** [comment]
Hi @changeworld , thanks so much for your feedback. We are looking at this issue now.

**Comment by shrijap** [comment]
Hi @changeworld. Thank you for reaching out to us.
The points on the leaderboard are calculated based on suggestions and not entire pull requests. For example, if you submitted a PR with 5 suggestions, and all 5 were approved, you would receive 375 points (15 points for each suggestion submitted, and 60 additional points for each suggestion that was approved). While you may have submitted 10,000 pull requests, we see that you have a total of 47754 suggestions. Hope this makes sense! If you still feel there something discrepant, please let us know!
