### ISSUE TITLE
Chinese (Simplified) translation error/improvement for VSCode

### ISSUE THREAD

**Issue by davidxuang** [microsoft/Localization#87]
Product: Visual Studio Code 1.38.1 with Language Pack 1.38.4

![image](https://user-images.githubusercontent.com/24728204/66268848-181e4c80-e874-11e9-8dbb-1d2d732714c8.png)

- “Create new branch from” may be translated to “创建新的分支从” or “从 ref 创建新的分支”; the current translation “创建新的分支机构” seems to be translated from “Create new branch form/firm”, since “机构” means “organization”.

![image](https://user-images.githubusercontent.com/24728204/66268918-c1654280-e874-11e9-86af-30d994096cfa.png)

- “操场” is the literal translation of “playground” but leads to confusion for native speakers. The previous translation “演练场” is not so good as well, but better than this one.

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by davidxuang** [comment]
![image](https://user-images.githubusercontent.com/24728204/68472821-58e6f800-025c-11ea-8f85-cf056fdef674.png)
Hmmm, it seems that there was some mistakes while fixing...

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

SRC:	$(plus) Create new branch from...
new tgt: $(plus) 从特定位置创建新的分支...
