### ISSUE TITLE
Adding a language to microsoft Localization.

### ISSUE THREAD

**Issue by NavruzbekNoraliev** [microsoft/Localization#89]
![Screenshot_1](https://user-images.githubusercontent.com/44977644/68920062-f3cc5e80-0795-11ea-8886-b9c8899e6c9e.png)
Dear Microsoft team
I want to contribute to localization but I could not find my language there, I would be grateful if you add the Uzbek language as well.

**Comment by shrijap** [comment]
Hi @NavruzbekNoraliev 

Thank you for reaching out to us and apologies for the delay in response!
We have decommissioned MLCP on April 8th, 2020 and are working on bringing you a new, more robust community localization platform. As per this, we are placing new language requests on hold for the time being. Please see the [Wiki](https://github.com/Microsoft/Localization/wiki) for more details, and watch for updates!

Best,
Shrija
