### ISSUE TITLE
German translation error in VS Code

### ISSUE THREAD

**Issue by gjungb** [microsoft/Localization#90]
The phrase `Open` currently gets translated to `Eröffnungskurs`, which basically means [opening price](https://www.linguee.de/englisch-deutsch/uebersetzung/opening+price.html).

My suggestion: replace with `Öffnen` [öffnen](https://www.linguee.de/deutsch-englisch/uebersetzung/%C3%B6ffnen.html).

![image](https://user-images.githubusercontent.com/3391068/70926236-0ce25c80-202d-11ea-8748-69654fc77143.png)

![image](https://user-images.githubusercontent.com/3391068/70926728-e4a72d80-202d-11ea-9f51-c60e752b924c.png)

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by gjungb** [comment]
Thx
