### ISSUE TITLE
Chinese (Simplified) translation mistake

### ISSUE THREAD

**Issue by OkazakiNagisa** [microsoft/Localization#91]
VS Code 1.41.1
Chinese (Simplified) Language Pack for Visual Studio Code 1.41.2

Developer: Inspect Key Mappings (JSON)
开发者：检查密钥映射（JSON）

'Key' should be translated to “按键” or “键盘”, but not “密钥”, and now there's no way in MLCP website to report mistakes like this.

**Comment by lukaschal** [comment]
Fixed.

new tgt: 检查按键映射（JSON）
