### ISSUE TITLE
German translation errors in URL opening dialog

### ISSUE THREAD

**Issue by JayEn84** [microsoft/Localization#92]
Since I did not find the corresponding strings within MLCP, I am submitting this issue.

When I ctrl+click on a URL of an unconfigured domain within a code file, a popup is asking me what I want to do, e.g. opening the URL in my browser. The German translations are partially wrong.

![grafik](https://user-images.githubusercontent.com/4518738/72159457-ad256a00-33bc-11ea-8f24-af2063c3b17b.png)

Left button:
English: "Open"
Current, wrong German translation: "Eröffnungskurs"
Corrected German translation: "Öffnen"

Right button:
English: "Configure trusted domains"
Current, wrong German translation: "Vertrauenswürdige Domänen konfigurieren"
Corrected German translation: "Vertrauenswürdige Domains konfigurieren"

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
This is a false positive: The contributor suggests replacing the confirmed term "Domänen" with "Domains", which is often used in the industry but is not MS terminology.

**Comment by JayEn84** [comment]
I understand, so please ignore my recommendation for the right button and correct the left one only.

**Comment by lukaschal** [comment]
Fixed.

src: Open
New tgt: Öffnen
