### ISSUE TITLE
Chinese (Simplified) Language has a error

### ISSUE THREAD

**Issue by WinXS** [microsoft/Localization#93]
![Snipaste_2020-02-12_09-08-40](https://user-images.githubusercontent.com/29294841/74293949-58885c80-4d77-11ea-990f-d0294bcf20c5.png)
Adress Bar：“面包屑”or“地址栏”？

**Comment by lukaschal** [comment]
On review.

src: Show &&Breadcrumbs
tgt: 显示面包屑(&&B)

**Comment by lukaschal** [comment]
Linguistic answer:

Current target is not proper. But 地址栏 is also not very accurate.

new tgt: 显示导航痕迹(&&B)

**Comment by shrijap** [comment]
@lukaschal can we close this issue out?

**Comment by lukaschal** [comment]
@shrijap Yes.
