### ISSUE TITLE
Willing to contribute for Telugu Language

### ISSUE THREAD

**Issue by YaminiKumarBoyapati** [microsoft/Localization#94]
Hi There, @aldonetti, I am willing to contribute to include Telugu, let me know how can I help.

**Comment by shrijap** [comment]
Hi @YaminiKumarBoyapati 

Thank you for reaching out to us and apologies for the delay in response! 
We have decommissioned MLCP on April 8th, 2020 and are working on bringing you a new, more robust community localization platform. As per this, we are placing new language requests on hold for the time being. Please see the [Wiki](https://github.com/Microsoft/Localization/wiki) for more details, and watch for updates! 

Best, 
Shrija
