### ISSUE TITLE
Update CONTRIBUTING.md in all localization repositories

### ISSUE THREAD

**Issue by matarillo** [microsoft/Localization#95]
You should clarify [the current (temporary) policy](https://github.com/Microsoft/Localization/wiki/MTEngineUpdate);

> We are _temporarily_ deactivating the community contributions on Machine Translated (MT) content.

## Repositories to be affected

- MicrosoftDocs/(repo name).(language)-(region)
  - eg. [MicrosoftDocs/azure-docs.zh-cn](https://github.com/MicrosoftDocs/azure-docs.zh-cn)
- dotnet/docs.(language)-(region)
  - eg. https://github.com/dotnet/docs.ja-jp
- and so on...

## Evidence of unexpected behaviors

https://github.com/dotnet/docs.ja-jp/pulls?q=label%3ADeclined

**Comment by shrijap** [comment]
Hi @matarillo 

Thank you for reaching out to us and apologies for the delay in response. 
Did you want a list of affected repos here?
