### ISSUE TITLE
Chinese (Simplified) translation inconsistent names

### ISSUE THREAD

**Issue by mcwindy** [microsoft/Localization#96]
![image](https://user-images.githubusercontent.com/40684304/76330265-96ea4a80-6328-11ea-9c9e-64cebd54e11c.png)
"向左移动面板", “将面板移动到右侧” and "将面板移至底部"
Maybe it's better to rename them to "将面板移至左侧", "将面板移至右侧", and "将面板移至底部".

**Comment by lukaschal** [comment]
Move Panel Left
向左移动面板

Move Panel Right
将面板移动到右侧

Move Panel To Bottom
将面板移至底部

**Comment by gucong3000** [comment]
Move Panel Left
将面板移至左侧

Move Panel Right
将面板移至右侧

Move Panel To Bottom
将面板移至底部

**Comment by lukaschal** [comment]
Fixed as per below:

Move Panel Left - 将面板移至左侧
Move Panel Right -将面板移至右侧
Move Panel To Bottom - 将面板移至底部
