### ISSUE TITLE
Chinese (Simplified) translation explorer missing button

### ISSUE THREAD

**Issue by maxiaozhi** [microsoft/Localization#97]
version:vscode1.43
左侧资源管理器未打开项目和文件夹时缺少相关按钮
在简体中文时：缺少“打开文件夹”和“克隆存储库”按钮，切换为“英文”显示时则正常
繁体中文时，缺少“打开文件夹”按钮，但“复制存放仓库”按钮（对应简体中文的“克隆存储库”）可以显示，因此推断有可能是翻译不完整或者其他原因导致
![avatar](https://s2.ax1x.com/2020/03/11/8k8EAs.png)
![avatar](https://s2.ax1x.com/2020/03/11/8k8k7j.png)

**Comment by lukaschal** [comment]
"view.workbench.cloneRepository": "You can also clone a repository from a URL. To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm).\n[Clone Repository](command:git.clone)"
"view.workbench.cloneRepository": "还可从 URL 克隆存储库。要详细了解如何在 VS Code 中使用 Git 和源代码管理，[请阅读我们的文档](https://aka.ms/vscode-scm)。\n[克隆存储库](命令: git.clone)"

You have not yet opened a folder. [Open Folder](command:{0})
你尚未打开文件夹。 [打开文件夹](命令: {0})

**Comment by EinsteinZheng** [comment]
I met the problem for about 3 days.
![截屏2020-03-11下午9 52 11](https://user-images.githubusercontent.com/17005509/76424193-df663e80-63e2-11ea-8845-63c67f22fb69.png)
![截屏2020-03-11下午9 51 25](https://user-images.githubusercontent.com/17005509/76424204-e2f9c580-63e2-11ea-9cb2-dd830be08f86.png)

**Comment by Andrew-Tuen** [comment]
I have the same problem. 
the  "run and debug", "open folder" button disappeared when i use Chinese (Simplified)

**Comment by janbaltus** [comment]
Fixed in 1.43.7 LP

**Comment by maxiaozhi** [comment]
> Fixed in 1.43.7 LP

Thanks!
