### ISSUE TITLE
Chinese (Simplified) menu bar 

### ISSUE THREAD

**Issue by lsbbd** [microsoft/Localization#98]
VS Code  1.43.0
Chinese (Simplified) Language Pack for Visual Studio Code 1.43.7

The macos menu bar "Run" menu item has extra parentheses

![image](https://user-images.githubusercontent.com/18237955/76733914-b22bde80-679c-11ea-8d85-98be57664647.png)

**Comment by janbaltus** [comment]
@dbaeumer  can you please help us to find the rootacuse?
Windows version HK is presnt and work as expected.
![image](https://user-images.githubusercontent.com/18324209/76845201-c9230d00-683e-11ea-9a79-99fcb55ad369.png)

**Comment by janbaltus** [comment]
Please test using 1.43.8 LP which was just published

**Comment by dbaeumer** [comment]
How do the translations look like?

**Comment by lsbbd** [comment]
> Please test using 1.43.8 LP which was just published

After updating to 1.43.8, the language cannot be switched to the Chinese

**Comment by janbaltus** [comment]
It was caused by BOM  in one file.
Please use 1.43.9

**Comment by lsbbd** [comment]
@janbaltus 1.43.9 fixed, thank you
