### ISSUE TITLE
vscode设置中文无效，version 1.43.8有个致命bug！

### ISSUE THREAD

**Issue by EDSpower** [microsoft/Localization#99]
设置了英文再设置中文无效，降级再设置中文即可！

**Comment by Renhongqiang** [comment]
1.43.8确实有bug

**Comment by janbaltus** [comment]
PLease update to 1.43.9 LP version

**Comment by CallMeR** [comment]
version 1.43.1 也有中文设置失败问题啊！

**Comment by shrijap** [comment]
@janbaltus what is the status here?

**Comment by janbaltus** [comment]
Do you have same issues with 1.44 version?
Latest LP for 1.43.11 also fixed this issue.
